### ISSUE TITLE
Add yourself to Staff as TA in 2024 Syllabus

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/Fluvial-Geomorphology#10]
Please add your photo, title, and such. Shout if you need help editing the div blocks. They are a little tricky.

**Comment by joewheaton** [comment]
Actually, I took care of it for you. 
![image](https://github.com/Riverscapes/Fluvial-Geomorphology/assets/9723905/f23be8af-6fee-461d-a0bf-a108707e5b7e)

Edit if you want to change anything.

**Comment by aarditti** [comment]
Looks good to me, thanks!
