### ISSUE TITLE
Canvas, WebPage, Repo Updates

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/Fluvial-Geomorphology#3]
## [Canvas](https://usu.instructure.com/courses/698781/assignments/syllabus)
- [x] Update Link to Syllabus to 2022
- [x] Confirm and update 

a) due dates on assignments, (delete text reference to specific date), 
b) confirm links are to correct chapter and module, and 
c) confirm there is a discussion that is linked.

- [x] Make sure that Modules link to correct chapters. 
(*chapter 15 has not yet been created, that link will need to be updated when content is created*)

## [Github Pages](https://riverscapes.github.io/Fluvial-Geomorphology/syllabus/)
- [x] Add CRNs to [Syllabus page for Spring 2022](https://riverscapes.github.io/Fluvial-Geomorphology/syllabus/2022_Spring.html)
- [x] Confirm dates and times are correct

### Github Repo
- [x] Add Milestones by Week for Course

**Comment by lauren-herbine** [comment]
@joewheaton no rush, but I think you need to push your changes that you made in NOLA

**Comment by joewheaton** [comment]
> @joewheaton no rush, but I think you need to push your changes that you made in NOLA

Cool. Thanks for reminder. I'll track that down.

**Comment by joewheaton** [comment]
@lauren-herbine as best I can tell, those were uploaded.

**Comment by lauren-herbine** [comment]
@joewheaton , huh, ok, thanks! Not entirely sure why I was having issues then.
