### ISSUE TITLE
Book the Geology 101 Classroom for Flume lab on Monday, February 7th

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/Fluvial-Geomorphology#7]
Talk to Joel Pederson and schedule for that afternoon.

**Comment by lauren-herbine** [comment]
From Joel:   So there should be no teaching conflicts with Fluvial Geomorph lab on Monday the 7th of Feb.

That afternoon we are slated to have our Geo Bake Off event -- this is our departmental riff on the Great British Baking Show, and is just for fun.  **And so there may be some hubbub and some good looking desserts around during the lab time.**
