### ISSUE TITLE
Please upload remaining chapters to Files

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/Fluvial-Geomorphology#8]
Hi @lauren-herbine 
Do you have the remaining chapters as PDFs by chance from last term. IF so, can you dump them in here
 please: https://usu.instructure.com/courses/698781/files/folder/Book

**Comment by lauren-herbine** [comment]
Shoot, ran out of downloads. Don't have them from last year, but I'll figure out the remaining chapters.

**Comment by joewheaton** [comment]
Just following up @lauren-herbine

**Comment by lauren-herbine** [comment]
Unfortunately it only let's me download 3 chapters at a time (maybe a week?). I'll see if I can get Shelby to help me get the last 4

**Comment by lauren-herbine** [comment]
All the chapters are uploaded, let me know if you want me to work on the supplemental stuff as well
